version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          PROJECT_NAME: beyondcoding/dockerwebapp
    working_directory: ~/trainingdocker
    steps:
    - checkout
    - run:
        name: Testing
        command: mvn test
    - setup_remote_docker
    - run:
        name: Install Docker client
        command: |
          set -x
          VER="17.03.0-ce"
          curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
          tar -xz -C /tmp -f /tmp/docker-$VER.tgz
          sudo cp -r /tmp/docker/* /usr/bin
    - run:
        name: Deploy to DockerHub
        command: |
          mvn clean package -DskipTests=true
          docker build -t $PROJECT_NAME .
          docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"
          docker push $PROJECT_NAME